CREATE TABLE IF NOT EXISTS FEED_STRUCTURE (
  FEED_ID BIGINT(10) NOT NULL,
  START_URL VARCHAR(255) NOT NULL,
  STORY  VARCHAR (1255),
  TITLE  VARCHAR (1255),
  LINK   VARCHAR (1255),
  SUMMARY VARCHAR (1255),
  CONTENT VARCHAR (1255),
  AUTHOR VARCHAR (1255),
  CREATED VARCHAR (1255),
  UPDATED VARCHAR (1255),
  PRIMARY KEY (FEED_ID)
) ;

-- new version
ALTER TABLE FEED_STRUCTURE ADD START VARCHAR(1255);

CREATE TABLE IF NOT EXISTS USER_STAT (
  USER_ID BIGINT(10) NOT NULL,
  FEED_ID BIGINT(10) NOT NULL,
  STORY_ID BIGINT(10) NOT NULL,
  HASREAD TINYINT DEFAULT 0,
  HASLIKE TINYINT DEFAULT 0,
  START_FROM TIMESTAMP DEFAULT '2000-01-01 00:00:00',
  COMMENT TEXT,
  CONTENT TEXT,
  PRIMARY KEY (USER_ID,FEED_ID,STORY_ID)
) ;
-- START FROM IS KEY TO TRACK USER READ STATUS
-- Unread count will start to be tracked from this date defaulting to 2000/01/01


CREATE TABLE IF NOT EXISTS USER_FOLLOW (
  USER_ID BIGINT(10) NOT NULL,
  FOLLOWING BIGINT(10) NOT NULL,
  CREATED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ID,FOLLOWING)
) ;

