
CREATE TABLE IF NOT EXISTS USER_ACTION (
  TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ACT VARCHAR(255) NOT NULL,
  USER_ID BIGINT(10) NOT NULL,
  FEED_ID BIGINT(10) NOT NULL,
  STORY_ID BIGINT(10) NOT NULL,
  CONTENT TEXT
) ;

ALTER TABLE FEED_SOURCE ADD VISIT_COUNT BIGINT(10) DEFAULT 0;
ALTER TABLE FEED_SOURCE ADD UPDATE_COUNT BIGINT(10) DEFAULT 0; -- update count will include those without updates
ALTER TABLE FEED_SOURCE ADD REFRESH_COUNT BIGINT(10) DEFAULT 0; -- updates with new feed items
ALTER TABLE FEED_SOURCE ADD ERROR_COUNT BIGINT(10) DEFAULT 0;


ALTER TABLE FEED_SOURCE ADD AVG_REFRESH_DURATION BIGINT(10) DEFAULT 0; -- in millis
ALTER TABLE FEED_SOURCE ADD REFRESH_ITEMCOUNT BIGINT(10) DEFAULT 0; -- in millis


