CREATE TABLE IF NOT EXISTS  FEED_SOURCE (
  URL VARCHAR(255) NOT NULL,
  FEED_ID BIGINT(10) NOT NULL AUTO_INCREMENT,
  LAST_ETAG VARCHAR(100) NOT NULL,
  CHECKED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  LAST_URL VARCHAR(255) NOT NULL,
  ENCODING CHAR(15) NOT NULL,
  PRIMARY KEY (FEED_ID)
) ;

CREATE TABLE IF NOT EXISTS FEED_STORY (
  STORY_ID BIGINT(10) NOT NULL AUTO_INCREMENT,
  FEED_ID bigint(10) NOT NULL,
  TITLE VARCHAR(255)  NOT NULL,
  LINK VARCHAR(1000) NOT NULL,
  PUBLISHED timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATED timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  AUTHOR VARCHAR(50) NOT NULL,
  DESCRIPTION text NOT NULL,
  CONTENT text NOT NULL,
  PRIMARY KEY (STORY_ID)
) ;

CREATE TABLE IF NOT EXISTS USER_INFO (
  USER_ID BIGINT(10) NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(255)  NOT NULL,
  PREF text NOT NULL,
  PRIMARY KEY (USER_ID)
) ;

CREATE TABLE IF NOT EXISTS USER_OPML (
  USER_ID BIGINT(10) NOT NULL,
  RAW text NOT NULL,
  PRIMARY KEY (USER_ID)
) ;

CREATE TABLE IF NOT EXISTS USER_STORY (
  USER_ID BIGINT(10) NOT NULL,
  STORY_ID BIGINT(10) NOT NULL,
  HASREAD TINYINT DEFAULT 0,
  HASLIKE TINYINT DEFAULT 0,
  COMMENT TEXT,
  PRIMARY KEY (USER_ID,STORY_ID)
) ;

CREATE TABLE IF NOT EXISTS AUTH_USER (
  USER_ID BIGINT(10) NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(255)  NOT NULL,
  NAME  VARCHAR(255),
  PASS  VARCHAR(255),
  APIKEY  VARCHAR(255),
  LASTLOGIN_FROM VARCHAR(255),
  LASTLOGIN_TIME TIMESTAMP,
  PRIMARY KEY (USER_ID)
) ;

